Import the libraries

In [1]:
import pandas as pd
import numpy as np

print("pandas version:", pd.__version__)
print("numpy version:", np.__version__)

pandas version: 2.2.3
numpy version: 2.1.3

In [63]:
import joblib

In [15]:
df = pd.read_csv(r"D:\project\data\raw\customer_churn.csv")

print(df.shape)

(999999, 32)

In [16]:
df.rename(columns={'ch': 'churn'}, inplace=True)

In [17]:
df.head()

,customer_id,signup_date,age,gender,annual_income,education,marital_status,dependents,tenure,contract,...,has_streaming_tv,has_streaming_movies,customer_satisfaction,num_complaints,num_service_calls,late_payments,avg_monthly_gb,days_since_last_interaction,credit_score,churn
0,CUST0000000002,2022-01-13 12:53:58.199973,18,Male,60786.11,master,married,1,22,one_year,...,0,1,7.0,0.0,3,1,63.25,134,585.0,0
1,CUST0000000003,2023-09-04 12:53:58.199985,38,Female,73184.32,high_school,widowed,0,3,two_year,...,1,0,6.0,1.0,1,0,47.77,11,632.0,0
2,CUST0000000004,2022-06-27 12:53:58.199992,44,Male,40923.78,high_school,married,1,6,two_year,...,0,1,5.0,2.0,2,1,50.82,6,569.0,0
3,CUST0000000005,2022-12-08 12:53:58.199999,45,Female,36400.94,bachelor,single,0,9,two_year,...,0,1,8.0,1.0,1,0,16.74,18,657.0,0
4,CUST0000000006,2023-01-12 12:53:58.200006,55,Female,30771.38,master,married,1,47,two_year,...,1,1,8.0,0.0,0,0,24.56,22,702.0,0

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999999 entries, 0 to 999998
Data columns (total 32 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   customer_id                  999999 non-null  object
 1   signup_date                  999999 non-null  object
 2   age                          999999 non-null  int64
 3   gender                       999999 non-null  object
 4   annual_income                970040 non-null  float64
 5   education                    999999 non-null  object
 6   marital_status               999999 non-null  object
 7   dependents                   999999 non-null  int64
 8   tenure                       999999 non-null  int64
 9   contract                     999999 non-null  object
 10  payment_method               999999 non-null  object
 11  paperless_billing            999999 non-null  object
 12  senior_citizen               999999 non-null  int64
 13  monthlycharges               999999 non-null  float64
 14  totalcharges                 999999 non-null  float64
 15  num_services                 999999 non-null  int64
 16  has_phone_service            999999 non-null  int64
 17  has_internet_service         999999 non-null  int64
 18  has_online_security          999999 non-null  int64
 19  has_online_backup            999999 non-null  int64
 20  has_device_protection        999999 non-null  int64
 21  has_tech_support             999999 non-null  int64
 22  has_streaming_tv             999999 non-null  int64
 23  has_streaming_movies         999999 non-null  int64
 24  customer_satisfaction        980078 non-null  float64
 25  num_complaints               970093 non-null  float64
 26  num_service_calls            999999 non-null  int64
 27  late_payments                999999 non-null  int64
 28  avg_monthly_gb               949987 non-null  float64
 29  days_since_last_interaction  999999 non-null  int64
 30  credit_score                 959605 non-null  float64
 31  churn                        999999 non-null  int64
dtypes: float64(7), int64(17), object(8)
memory usage: 244.1+ MB

In [19]:
df.describe()

,age,annual_income,dependents,tenure,senior_citizen,monthlycharges,totalcharges,num_services,has_phone_service,has_internet_service,...,has_streaming_tv,has_streaming_movies,customer_satisfaction,num_complaints,num_service_calls,late_payments,avg_monthly_gb,days_since_last_interaction,credit_score,churn
count,999999.000000,970040.000000,999999.000000,999999.000000,999999.000000,999999.000000,999999.000000,999999.000000,999999.000000,999999.000000,...,999999.00000,999999.000000,980078.000000,970093.000000,999999.000000,999999.000000,949987.000000,999999.000000,959605.000000,999999.000000
mean,44.724605,58788.315753,0.799831,22.381943,0.199511,86.443720,1837.323131,2.563723,0.769551,0.849742,...,0.59999,0.549086,6.159107,0.701668,1.760250,0.400969,39.095105,44.494219,678.562134,0.099227
std,14.479475,37137.452031,0.893655,20.073341,0.399633,27.592437,1803.721741,1.412330,0.421121,0.357324,...,0.48990,0.497585,2.328286,0.838148,1.485677,0.633289,43.852528,44.922601,87.642951,0.298967
min,18.000000,20000.000000,0.000000,1.000000,0.000000,20.000000,16.300000,1.000000,0.000000,0.000000,...,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,300.000000,0.000000
25%,34.000000,32712.555000,0.000000,6.000000,0.000000,70.490000,484.535000,1.000000,1.000000,1.000000,...,0.00000,0.000000,4.000000,0.000000,1.000000,0.000000,12.840000,12.000000,619.000000,0.000000
50%,44.000000,48954.595000,1.000000,16.000000,0.000000,85.480000,1249.750000,2.000000,1.000000,1.000000,...,1.00000,1.000000,7.000000,1.000000,1.000000,0.000000,27.770000,31.000000,680.000000,0.000000
75%,55.000000,73475.170000,1.000000,33.000000,0.000000,100.680000,2617.660000,3.000000,1.000000,1.000000,...,1.00000,1.000000,8.000000,1.000000,3.000000,1.000000,51.230000,62.000000,740.000000,0.000000
max,90.000000,250000.000000,5.000000,72.000000,1.000000,854.956730,16252.861508,6.000000,1.000000,1.000000,...,1.00000,1.000000,9.000000,7.000000,12.000000,5.000000,557.824023,365.000000,850.000000,1.000000

In [20]:
df.isnull().sum()

customer_id                        0
signup_date                        0
age                                0
gender                             0
annual_income                  29959
education                          0
marital_status                     0
dependents                         0
tenure                             0
contract                           0
payment_method                     0
paperless_billing                  0
senior_citizen                     0
monthlycharges                     0
totalcharges                       0
num_services                       0
has_phone_service                  0
has_internet_service               0
has_online_security                0
has_online_backup                  0
has_device_protection              0
has_tech_support                   0
has_streaming_tv                   0
has_streaming_movies               0
customer_satisfaction          19921
num_complaints                 29906
num_service_calls                  0
late_payments                      0
avg_monthly_gb                 50012
days_since_last_interaction        0
credit_score                   40394
churn                              0
dtype: int64

In [21]:
(df.isnull().sum() / len(df) * 100).round(1)

customer_id                    0.0
signup_date                    0.0
age                            0.0
gender                         0.0
annual_income                  3.0
education                      0.0
marital_status                 0.0
dependents                     0.0
tenure                         0.0
contract                       0.0
payment_method                 0.0
paperless_billing              0.0
senior_citizen                 0.0
monthlycharges                 0.0
totalcharges                   0.0
num_services                   0.0
has_phone_service              0.0
has_internet_service           0.0
has_online_security            0.0
has_online_backup              0.0
has_device_protection          0.0
has_tech_support               0.0
has_streaming_tv               0.0
has_streaming_movies           0.0
customer_satisfaction          2.0
num_complaints                 3.0
num_service_calls              0.0
late_payments                  0.0
avg_monthly_gb                 5.0
days_since_last_interaction    0.0
credit_score                   4.0
churn                          0.0
dtype: float64

In [22]:
num_cols = [
    'avg_monthly_gb',
    'credit_score',
    'num_complaints',
    'annual_income',
    'customer_satisfaction'
]

for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)

C:\Users\OVER CLOCK\AppData\Local\Temp\ipykernel_21232\2621823540.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [23]:
df[num_cols].isnull().sum()

avg_monthly_gb           0
credit_score             0
num_complaints           0
annual_income            0
customer_satisfaction    0
dtype: int64

In [ ]:
df.select_dtypes(include='object').columns

Index(['customer_id', 'signup_date', 'gender', 'education', 'marital_status',
       'contract', 'payment_method', 'paperless_billing'],
      dtype='object')

# Encoding

Ordinal Encoding : Education , Contract , Paperless Billing

One Hot Coding : Gender , Martial Status , Payment Method

The solution is mapping

In [ ]:
df = df.drop(columns=['customer_id', 'signup_date'])

In [ ]:
df['contract']= df['contract'].map({'month_to_month': 0, 'one_year': 1, 'two_year': 2})

In [30]:
df['paperless_billing'].value_counts()

paperless_billing
Yes    749879
No     250120
Name: count, dtype: int64

In [31]:
df['paperless_billing'] = df['paperless_billing'].map({'Yes': 1, 'No': 0})

In [32]:
df['paperless_billing'].value_counts()

paperless_billing
1    749879
0    250120
Name: count, dtype: int64

In [33]:
df['education'].value_counts()

education
bachelor       300324
college        249609
high_school    249348
master         150468
phd             50250
Name: count, dtype: int64

In [34]:
df['education'] = df['education'].map({
    'high_school': 0,
    'college': 1,
    'bachelor': 2,
    'master': 3,
    'phd': 4
})

In [35]:
df['education'].value_counts()

education
2    300324
1    249609
0    249348
3    150468
4     50250
Name: count, dtype: int64

In [36]:
df = pd.get_dummies(df, columns=[
    'gender',
    'marital_status',
    'payment_method'
])

In [37]:
df.isnull().sum()

age                                0
annual_income                      0
education                          0
dependents                         0
tenure                             0
contract                           0
paperless_billing                  0
senior_citizen                     0
monthlycharges                     0
totalcharges                       0
num_services                       0
has_phone_service                  0
has_internet_service               0
has_online_security                0
has_online_backup                  0
has_device_protection              0
has_tech_support                   0
has_streaming_tv                   0
has_streaming_movies               0
customer_satisfaction              0
num_complaints                     0
num_service_calls                  0
late_payments                      0
avg_monthly_gb                     0
days_since_last_interaction        0
credit_score                       0
churn                              0
gender_Female                      0
gender_Male                        0
gender_Other                       0
marital_status_divorced            0
marital_status_married             0
marital_status_single              0
marital_status_widowed             0
payment_method_bank_transfer       0
payment_method_credit_card         0
payment_method_electronic_check    0
payment_method_mailed_check        0
dtype: int64

In [38]:
df.describe()

,age,annual_income,education,dependents,tenure,contract,paperless_billing,senior_citizen,monthlycharges,totalcharges,...,has_streaming_tv,has_streaming_movies,customer_satisfaction,num_complaints,num_service_calls,late_payments,avg_monthly_gb,days_since_last_interaction,credit_score,churn
count,999999.000000,999999.000000,999999.000000,999999.000000,999999.000000,999999.000000,999999.000000,999999.000000,999999.000000,999999.000000,...,999999.00000,999999.000000,999999.000000,999999.000000,999999.000000,999999.000000,999999.000000,999999.000000,999999.000000,999999.000000
mean,44.724605,58493.707019,1.502663,0.799831,22.381943,1.409547,0.749880,0.199511,86.443720,1837.323131,...,0.59999,0.549086,6.175858,0.710590,1.760250,0.400969,38.528713,44.494219,678.620216,0.099227
std,14.479475,36615.316546,1.162380,0.893655,20.073341,0.530851,0.433082,0.399633,27.592437,1803.721741,...,0.48990,0.497585,2.307972,0.827082,1.485677,0.633289,42.813110,44.922601,85.855043,0.298967
min,18.000000,20000.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,20.000000,16.300000,...,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,300.000000,0.000000
25%,34.000000,33185.450000,1.000000,0.000000,6.000000,1.000000,0.000000,0.000000,70.490000,484.535000,...,0.00000,0.000000,5.000000,0.000000,1.000000,0.000000,13.620000,12.000000,622.000000,0.000000
50%,44.000000,48954.595000,2.000000,1.000000,16.000000,1.000000,1.000000,0.000000,85.480000,1249.750000,...,1.00000,1.000000,7.000000,1.000000,1.000000,0.000000,27.770000,31.000000,680.000000,0.000000
75%,55.000000,72420.510000,2.000000,1.000000,33.000000,2.000000,1.000000,0.000000,100.680000,2617.660000,...,1.00000,1.000000,8.000000,1.000000,3.000000,1.000000,49.420000,62.000000,737.000000,0.000000
max,90.000000,250000.000000,4.000000,5.000000,72.000000,2.000000,1.000000,1.000000,854.956730,16252.861508,...,1.00000,1.000000,9.000000,7.000000,12.000000,5.000000,557.824023,365.000000,850.000000,1.000000

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999999 entries, 0 to 999998
Data columns (total 38 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   age                              999999 non-null  int64
 1   annual_income                    999999 non-null  float64
 2   education                        999999 non-null  int64
 3   dependents                       999999 non-null  int64
 4   tenure                           999999 non-null  int64
 5   contract                         999999 non-null  int64
 6   paperless_billing                999999 non-null  int64
 7   senior_citizen                   999999 non-null  int64
 8   monthlycharges                   999999 non-null  float64
 9   totalcharges                     999999 non-null  float64
 10  num_services                     999999 non-null  int64
 11  has_phone_service                999999 non-null  int64
 12  has_internet_service             999999 non-null  int64
 13  has_online_security              999999 non-null  int64
 14  has_online_backup                999999 non-null  int64
 15  has_device_protection            999999 non-null  int64
 16  has_tech_support                 999999 non-null  int64
 17  has_streaming_tv                 999999 non-null  int64
 18  has_streaming_movies             999999 non-null  int64
 19  customer_satisfaction            999999 non-null  float64
 20  num_complaints                   999999 non-null  float64
 21  num_service_calls                999999 non-null  int64
 22  late_payments                    999999 non-null  int64
 23  avg_monthly_gb                   999999 non-null  float64
 24  days_since_last_interaction      999999 non-null  int64
 25  credit_score                     999999 non-null  float64
 26  churn                            999999 non-null  int64
 27  gender_Female                    999999 non-null  bool
 28  gender_Male                      999999 non-null  bool
 29  gender_Other                     999999 non-null  bool
 30  marital_status_divorced          999999 non-null  bool
 31  marital_status_married           999999 non-null  bool
 32  marital_status_single            999999 non-null  bool
 33  marital_status_widowed           999999 non-null  bool
 34  payment_method_bank_transfer     999999 non-null  bool
 35  payment_method_credit_card       999999 non-null  bool
 36  payment_method_electronic_check  999999 non-null  bool
 37  payment_method_mailed_check      999999 non-null  bool
dtypes: bool(11), float64(7), int64(20)
memory usage: 216.5 MB

# Check Duplicates

In [41]:
df.duplicated().sum()

np.int64(0)

## Outlier Handling

Outliers were analyzed using the IQR method.

No outliers were removed because extreme values may represent valid customer behavior and can provide important information for churn prediction.

In [42]:
# Numerical columns

numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

print(f"Number of numerical columns: {len(numerical_cols)}")
numerical_cols.tolist()

Number of numerical columns: 27

['age',
 'annual_income',
 'education',
 'dependents',
 'tenure',
 'contract',
 'paperless_billing',
 'senior_citizen',
 'monthlycharges',
 'totalcharges',
 'num_services',
 'has_phone_service',
 'has_internet_service',
 'has_online_security',
 'has_online_backup',
 'has_device_protection',
 'has_tech_support',
 'has_streaming_tv',
 'has_streaming_movies',
 'customer_satisfaction',
 'num_complaints',
 'num_service_calls',
 'late_payments',
 'avg_monthly_gb',
 'days_since_last_interaction',
 'credit_score',
 'churn']

In [43]:
# Detect outliers using IQR

outlier_summary = []

for col in numerical_cols:
    
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = df[
        (df[col] < lower_bound) |
        (df[col] > upper_bound)
    ]
    
    outlier_summary.append({
        'Feature': col,
        'Outlier Count': len(outliers),
        'Outlier Percentage': round((len(outliers)/len(df))*100, 2)
    })

outlier_df = pd.DataFrame(outlier_summary)

outlier_df.sort_values(
    by='Outlier Percentage',
    ascending=False
).head(15)

                        Feature  Outlier Count  Outlier Percentage
11            has_phone_service         230449               23.04
7                senior_citizen         199511               19.95
12         has_internet_service         150258               15.03
26                        churn          99227                9.92
23               avg_monthly_gb          63898                6.39
2                     education          50250                5.03
1                 annual_income          48960                4.90
3                    dependents          47406                4.74
24  days_since_last_interaction          47040                4.70
9                  totalcharges          45654                4.57
20               num_complaints          33220                3.32
8                monthlycharges           9740                0.97
22                late_payments           7914                0.79
21            num_service_calls           7809                0.78
25                 credit_score           5104                0.51

In [44]:
bool_cols = df.select_dtypes(
    include='bool'
).columns

df[bool_cols] = df[bool_cols].astype(int)

In [45]:
print(df.shape)
df.head()

(999999, 38)

,age,annual_income,education,dependents,tenure,contract,paperless_billing,senior_citizen,monthlycharges,totalcharges,...,gender_Male,gender_Other,marital_status_divorced,marital_status_married,marital_status_single,marital_status_widowed,payment_method_bank_transfer,payment_method_credit_card,payment_method_electronic_check,payment_method_mailed_check
0,18,60786.11,3,1,22,1,1,0,71.54,1602.22,...,1,0,0,1,0,0,1,0,0,0
1,38,73184.32,0,0,3,2,0,0,112.20,328.81,...,0,0,0,0,0,1,0,1,0,0
2,44,40923.78,0,1,6,2,1,0,107.49,643.45,...,1,0,0,1,0,0,1,0,0,0
3,45,36400.94,2,0,9,2,1,0,110.05,648.79,...,0,0,0,0,1,0,0,1,0,0
4,55,30771.38,3,1,47,2,1,0,71.80,3041.87,...,0,0,0,1,0,0,0,1,0,0

# Data Spliting

# Train-Test Split

The dataset is divided into:

- Training Set (80%)
- Testing Set (20%)

Stratified sampling is used to preserve the churn distribution in both datasets.

In [47]:
X = df.drop(columns=['churn'])
y = df['churn']

In [49]:
import sklearn
print("sklearn version:", sklearn.__version__)

sklearn version: 1.6.1

In [52]:
X_train, X_test, y_train,y_test = sklearn.model_selection.train_test_split(
    X,y,test_size= 0.2 , random_state=42 ,stratify=y
)

In [53]:
print(f"Training samples: {X_train.shape[0]:,}")
print(f"Testing samples : {X_test.shape[0]:,}")

print(f"Train churn rate: {y_train.mean()*100:.2f}%")
print(f"Test churn rate : {y_test.mean()*100:.2f}%")

Training samples: 799,999
Testing samples : 200,000
Train churn rate: 9.92%
Test churn rate : 9.92%

# Feature Scaling

StandardScaler is applied to numerical features.

The scaler is fitted on the training set only to prevent data leakage.

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999999 entries, 0 to 999998
Data columns (total 38 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   age                              999999 non-null  int64
 1   annual_income                    999999 non-null  float64
 2   education                        999999 non-null  int64
 3   dependents                       999999 non-null  int64
 4   tenure                           999999 non-null  int64
 5   contract                         999999 non-null  int64
 6   paperless_billing                999999 non-null  int64
 7   senior_citizen                   999999 non-null  int64
 8   monthlycharges                   999999 non-null  float64
 9   totalcharges                     999999 non-null  float64
 10  num_services                     999999 non-null  int64
 11  has_phone_service                999999 non-null  int64
 12  has_internet_service             999999 non-null  int64
 13  has_online_security              999999 non-null  int64
 14  has_online_backup                999999 non-null  int64
 15  has_device_protection            999999 non-null  int64
 16  has_tech_support                 999999 non-null  int64
 17  has_streaming_tv                 999999 non-null  int64
 18  has_streaming_movies             999999 non-null  int64
 19  customer_satisfaction            999999 non-null  float64
 20  num_complaints                   999999 non-null  float64
 21  num_service_calls                999999 non-null  int64
 22  late_payments                    999999 non-null  int64
 23  avg_monthly_gb                   999999 non-null  float64
 24  days_since_last_interaction      999999 non-null  int64
 25  credit_score                     999999 non-null  float64
 26  churn                            999999 non-null  int64
 27  gender_Female                    999999 non-null  int64
 28  gender_Male                      999999 non-null  int64
 29  gender_Other                     999999 non-null  int64
 30  marital_status_divorced          999999 non-null  int64
 31  marital_status_married           999999 non-null  int64
 32  marital_status_single            999999 non-null  int64
 33  marital_status_widowed           999999 non-null  int64
 34  payment_method_bank_transfer     999999 non-null  int64
 35  payment_method_credit_card       999999 non-null  int64
 36  payment_method_electronic_check  999999 non-null  int64
 37  payment_method_mailed_check      999999 non-null  int64
dtypes: float64(7), int64(31)
memory usage: 289.9 MB

numerical features to be scaled 
['age','annual_income','dependents','tenure','monthlycharges','totalcharges','num_services','customer_satisfaction','num_complaints','num_service_calls','late_payments','avg_monthly_gb','days_since_last_interaction','credit_score']

In [59]:
scale_cols = [
    'age',
    'annual_income',
    'dependents',
    'tenure',
    'monthlycharges',
    'totalcharges',
    'num_services',
    'customer_satisfaction',
    'num_complaints',
    'num_service_calls',
    'late_payments',
    'avg_monthly_gb',
    'days_since_last_interaction',
    'credit_score'
]

In [60]:
scaler = sklearn.preprocessing.StandardScaler()

In [61]:
X_train[scale_cols] = scaler.fit_transform(X_train[scale_cols])
X_test[scale_cols] = scaler.transform(X_test[scale_cols])

In [62]:
X_train.head()

,age,annual_income,education,dependents,tenure,contract,paperless_billing,senior_citizen,monthlycharges,totalcharges,...,gender_Male,gender_Other,marital_status_divorced,marital_status_married,marital_status_single,marital_status_widowed,payment_method_bank_transfer,payment_method_credit_card,payment_method_electronic_check,payment_method_mailed_check
650335,-0.533508,0.185954,1,-0.894942,0.528553,2,1,0,1.382899,1.287850,...,1,0,0,1,0,0,0,1,0,0
154329,-1.569788,-0.582528,1,0.222985,-0.766990,1,1,0,-1.566696,-0.841426,...,0,0,0,1,0,0,0,1,0,0
9634,0.571858,1.590225,3,3.576766,2.471867,1,1,1,-0.276226,2.403989,...,1,0,0,0,1,0,0,0,1,0
244330,-0.326252,0.193589,2,0.222985,-0.816818,1,0,0,-0.782357,-0.811464,...,1,0,0,0,1,0,0,0,0,1
221213,2.575333,-0.605855,0,-0.894942,0.030267,1,0,0,-0.473396,-0.048765,...,1,0,0,1,0,0,0,0,1,0

# Save Processed Data & Scaler

In this step we save:
- Clean dataset (after preprocessing)
- Fitted scaler object for future use

In [73]:
train_df = X_train.copy()
train_df['churn'] = y_train.values

In [74]:
test_df = X_test.copy()
test_df['churn'] = y_test.values

In [75]:
clean_df = pd.concat([train_df, test_df], ignore_index=True)

In [76]:
clean_df.to_csv(r"D:\project\data\processed\clean_data.csv", index=False)

In [77]:
joblib.dump(scaler, r"D:\project\models\scaler\scaler.pk1")

['D:\\project\\models\\scaler\\scaler.pk1']